name: Build and Upload

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create new branch for release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b release-${{ github.event.release.tag_name }}
          cp -r dist/* .
          git add .
          git commit -m "Build files for release ${{ github.event.release.tag_name }}"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git release-${{ github.event.release.tag_name }}